# Generated by Django 2.2.24 on 2022-06-27 09:11

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220627_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                verbose_name='Нормализированный номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(
                related_name='Liked_flats',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кто лайкнул'),
        ),
    ]
