# Generated by Django 2.2.24 on 2022-06-27 11:25

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220627_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True,
                                         related_name='Liked_flats',
                                         to=settings.AUTH_USER_MODEL,
                                         verbose_name='Кто лайкнул'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, db_index=True,
                                           verbose_name='ФИО владельца')),
                ('owner_pure_phone',
                 phonenumber_field.modelfields.PhoneNumberField(
                    blank=True,
                    max_length=128, region=None, db_index=True,
                    verbose_name='Нормализированный номер владельца')),
                ('owners_phonenumber', models.CharField(blank=True,
                                                        max_length=20,
                                                        db_index=True,
                                                        verbose_name='Номер владельца')),
                ('flats', models.ManyToManyField(related_name='flats',
                                                 to='property.Flat',
                                                 verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
