# Generated by Django 2.2.24 on 2022-06-27 15:49

from django.db import migrations

def create_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner = Owner.objects.filter(id=flat.id).first()
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220627_1425'),
    ]

    operations = [
        migrations.RunPython(create_owner)
    ]
