# Generated by Django 2.2.24 on 2022-06-28 11:18

from django.db import migrations


class Migration(migrations.Migration):
    def add_owner_flat(apps, schema_editor):
        Owner = apps.get_model('property', 'Owner')
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            owner = Owner.objects.filter(owner=flat.owner).first()
            owner.flats.add(flat)

    dependencies = [
        ('property', '0010_auto_20220627_1849'),
    ]

    operations = [
        migrations.RunPython(add_owner_flat)
    ]
