# Generated by Django 2.2.24 on 2022-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20220629_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='compaint_text',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
    ]
