# Generated by Django 2.2.24 on 2022-06-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220630_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='compaint_text',
            new_name='text',
        ),
    ]
